# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: sqrl-os
description: A clean, Flatpak-only KDE gaming image with NVIDIA drivers for squirrels.

base-image: ghcr.io/ublue-os/kinoite-nvidia
image-version: 42

modules:
  - type: rpm-ostree
    remove:
      - firefox
      - firefox-langpacks

  - type: default-flatpaks@v1
    notify: true
    system:
      repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
      repo-name: flathub
      install:
        - org.mozilla.firefox
        - com.discordapp.Discord
        - com.valvesoftware.Steam
        - com.pokemmo.PokeMMO
        - com.vysp3r.ProtonPlus
        - org.libreoffice.LibreOffice
        - org.videolan.VLC
        - io.missioncenter.MissionCenter
        - com.protonvpn.www
        - org.openrgb.OpenRGB
